### ISSUE TITLE
Engine Tutorial

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/Malum-Game-Engine#10]
As a Team
We would like to understand GoDot
So that we can build a game

**Comment by denzuko** [comment]
@Himecchi has completed hers last week.

**Comment by narkane** [comment]
finished

**Comment by denzuko** [comment]
@JeremyDoss is there anyone left on this besides yourself?

**Comment by JeremyDoss** [comment]
I haven't finished it yet

On Oct 8, 2018 1:46 PM, "Dwight Spencer" <notifications@github.com> wrote:

@JeremyDoss <https://github.com/JeremyDoss> is there anyone left on this
besides yourself?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Dallas-Makerspace/Malum-Game-Engine/issues/10#issuecomment-427940547>,
or mute the thread

**Comment by JeremyDoss** [comment]
@denzuko I have been out of town but plan on closing this by this weekend

**Comment by denzuko** [comment]
Cool, thanks for the update. That was my plan to have it closed out once you've completed so we can move on to the more fun stuff.

**Comment by JeremyDoss** [comment]
@denzuko Done!
